### ISSUE TITLE
Option to disable left side bar (Document Outline)

### ISSUE THREAD

**Issue by SundaresanSelvaraj** [md-reader/md-reader#33]
Provide option to disable left side bar

**Comment by Heroor** [comment]
@SundaresanSelvaraj  Why don't you need a sidebar, don't you write heads on markdown?

**Comment by SundaresanSelvaraj** [comment]
@Heroor If there is option to disable to sidebar, we can get full view of markdown document. While traversing between headings, we can enable sidebar or use TOC

**Comment by Heroor** [comment]
Well, I don't think TOC is better than sidebar, but I can add a sidebar disable option or hide the sidebar just by clicking sidebar button.

**Comment by SundaresanSelvaraj** [comment]
Thanks @Heroor

**Comment by Heroor** [comment]
Hi, Chrome Web Wtore is pending review, here is the release https://github.com/md-reader/md-reader/releases/tag/v2.11.4.

**Comment by Heroor** [comment]
Hi! Just wanted to thank you for your support, there’s a gift waiting for you — please leave your email here so we can send it over 🎁

— Bener, Markdown Reader

**Comment by SundaresanSelvaraj** [comment]
@Heroor This is my mail id `sundaresans@altmail.kr`
