### ISSUE TITLE
可以增加多行文本合并为一行么?

### ISSUE THREAD

**Issue by yyangdid** [md-reader/md-reader#35]
例如我的 md 源文件如下:
``` md
# level1

这是第一行内容. 
这是第二行内容.
这是第三行内容.
```

现在 2.11.4 版本的渲染是 md 源文件有三行, 渲染也是显示三行. 可以让这种源文件连续的几行在渲染时合并为一行么(无换行), 把空行才作为真正的换行:
``` md
# level1

这是第一行内容. 
这是第二行内容.

这是第三行内容.
```
渲染时 第一二行视为一行, 第三行视为新行.

**Comment by Heroor** [comment]
`markdown-it` 默认是不换行处理的，我可以发布一个小版本恢复默认配置，后面考虑加一个开关选项来控制

**Comment by yyangdid** [comment]
好的, 谢谢 👍

**Comment by Heroor** [comment]
Fixes #72
