### ISSUE TITLE
Invalid manifest error while installing using chrome extension store

### ISSUE THREAD

**Issue by AleksNeStu** [md-reader/md-reader#36]
Install from the [chrome extension store](https://chrome.google.com/webstore/detail/md-reader/medapdbncneneejhbgcjceippjlfkmkg).

![image](https://user-images.githubusercontent.com/16610768/204764870-da45bd38-a05c-4adb-b9db-d9e8b62955bd.png)

**Comment by Heroor** [comment]
What is the browser version and operating system?

**Comment by Heroor** [comment]
Fixed in v2.12.2.
