### ISSUE TITLE
滚动条的主题不能随着插件中"主题"设置而变化

### ISSUE THREAD

**Issue by tawangwuhen** [md-reader/md-reader#42]
**Describe the bug**
将主题设置为“浅色”，滚动条依然是深色的
<img width="1800" alt="image" src="https://github.com/md-reader/md-reader/assets/23145193/2624e244-ba76-4293-9b0d-5c5e5d4717b7">

**Expected behavior**
像Github这样
浅色模式下的滚动条：
<img width="1800" alt="image" src="https://github.com/md-reader/md-reader/assets/23145193/8f6b010c-dce2-4b47-ac25-31e474bc4177">
深色模式下的滚动条
![image](https://github.com/md-reader/md-reader/assets/23145193/5737cab2-c290-4a65-b919-f094472ce373)

**Desktop:**
 - OS: macOS
 - Browser: Google Chrome
 - Version: 2.12.5

**Additional context**
- 在设置中开启了始终显示滚动条<img width="668" alt="image" src="https://github.com/md-reader/md-reader/assets/23145193/f5bf143d-f758-41b6-97a6-58427475abc0">
- 系统设置里的颜色模式设置为了深色模式
- 将插件的主题设置为"自动"，然后切换设备的主题，滚动条的颜色会正常的进行变化，如上图中的Github那样

**Comment by Heroor** [comment]
ok，我这几天改一下

**Comment by Heroor** [comment]
Hi! Just wanted to thank you for your support, there’s a gift waiting for you — please leave your email here so we can send it over 🎁

— Bener, Markdown Reader
