### ISSUE TITLE
请求上线 Firefox 版本

### ISSUE THREAD

**Issue by qinxs** [md-reader/md-reader#55]
### 需求原因

一些本地markdown文件需要翻译 使用 firefox + TWP - Translate Web Pages扩展 很方便
chrome浏览器里 不支持这样的简便操作

### 扩展功能测试

我这边用firefox临时加载测试 功能一切正常

popup窗口中的允许访问文件网址权限可以看心情隐藏一下（Firefox好像是默认拥有的）

![md-reader](https://github.com/md-reader/md-reader/assets/13647698/5b8da590-b3d8-4108-8cd8-c7face532478)

**Comment by Heroor** [comment]
好的，感谢测试！因为当时只是按 Chrome 的 API 来开发的，不确定能否全都适配 Firefox，我空闲时候看一下，尝试发布一个 Firefox 的版本

| |
BenjaVan
| |
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月25日 10:39 |
| 收件人 | md-reader/md-reader ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [md-reader/md-reader] 请求上线 Firefox 版本 (Issue #55) |

需求原因

一些本地markdown文件需要翻译 使用 firefox + TWP - Translate Web Pages扩展 很方便
chrome浏览器里 不支持这样的简便操作

扩展功能测试

我这边用firefox临时加载测试 功能一切正常

popup窗口中的允许访问文件网址权限可以看心情隐藏一下（Firefox好像是默认拥有的）

md-reader.png (view on web)

**Comment by Heroor** [comment]
1. 预览本地 Markdown 文件，Windows 应该没什么问题，在 macOS 上打开本地文件时，Firefox 会询问文件的打开方式或者直接下载此文件，无法加载成页面并通过附加组件渲染：
<img width="374" alt="image" src="https://github.com/md-reader/md-reader/assets/19926530/324797d1-c68a-497e-ba37-4727f260585b">

应该是 Firefox 没有把 Markdown 文件当做 text 类型，网络上有一些[解决方案](https://github.com/Cimbali/markdown-viewer#support-for-local-files-on-linux-and-macos)，我在 macOS 测试暂时还没有效果。

2. 预览在线资源，如果其网站严格执行 CSP，Firefox 会阻止附加组件的加载，例如 `https://raw.githubusercontent.com/*`，md-reader 将无法生效；不严格执行 CSP 的网站例如 GitLab 的资源：`https://gitlab.com/*` 是可以正常预览的。

**Comment by Heroor** [comment]
我不确定是 Firefox 更新了 markdown 文件的识别策略，还是之前修改了本机的 MIME 起作用了，亦或是其他原因，，，今天在 macOS-15.0 Beta 测试，所有协议（file://、http://、https:// ）的文件链接都可以在 Firefox 正常预览了！🎉
