### ISSUE TITLE
Word wrap for code blocks

### ISSUE THREAD

**Issue by zycdev** [md-reader/md-reader#58]
Very useful plugin! But when a line in a code block is too long, I have to scroll left or right to read it. I really wish it could support word wrap of code blocks.
<img width="811" alt="image" src="https://github.com/user-attachments/assets/9dc6e009-3b19-4582-a7fb-6b1c6dbad7d5">

**Comment by Heroor** [comment]
Great suggestion, I'll support it in subsequent releases!

**Comment by Heroor** [comment]
Version 2.15 has been released, please try it after updating, if you have any other suggestions, please keep them coming!

Enjoy using

**Comment by Heroor** [comment]
![CleanShot 2024-11-26 at 20 04 41](https://github.com/user-attachments/assets/e1d1ccfb-9df0-4e89-b6ce-3cfeeb20c8e2)
