### ISSUE TITLE
Unexpected margin at printing

### ISSUE THREAD

**Issue by FreeHarry** [md-reader/md-reader#60]
**Describe the bug**
When printing the markdown document, there should be no initial margins used. E.g. currently the document has a big left/right margin on print preview. And if the user selects a small paper format, the margin is unproportionally big, which seems buggy.

So the idea is to set the print margin to `0` for all sides, since the browser will control the print margin separately.

**To Reproduce**

1. Open a markdown document
2. Go to print Preview
    - Choose in browser => Margins: None => The text should be rendered without margins. But it isn't.
    - or Select a small Paper size => The margin is unproportionally big

**Expected behavior**
In print preview and while printing the margins should be initially `0` on all sides. Browser handles margins separately.

**Comment by Heroor** [comment]
You're right, I'll improve. Thank you!

**Comment by Heroor** [comment]
Version 2.16 has been released, please try after updating, if you have other questions, please continue to ask, thank you for your use!
