### ISSUE TITLE
Global Option: Always hide side panel at printing

### ISSUE THREAD

**Issue by FreeHarry** [md-reader/md-reader#61]
Currently the side panel is printed if it is shown and not if hidden. But usually I don't want the side panel on prints. So I have to hide it before printing and shown it after printing.

A global option like, `Always hide side panel at printing`, would improve the behavior.

**Comment by Heroor** [comment]
The original design was to manually control the folding of the sidebar before printing. If there is always a need to turn the sidebar off while printing, I can add a setting to control it.

**Comment by FreeHarry** [comment]
Would be great to have such setting 👍

**Comment by Heroor** [comment]
In another issue, the print layout will no longer include margins. However, allowing a sidebar to be displayed could disrupt the layout, negatively impact the print appearance, and look less aesthetically pleasing. Therefore, I believe the sidebar and margins should be uniformly removed during printing, and no options for them should be provided.
What do you think?

**Comment by FreeHarry** [comment]
> In another issue, the print layout will no longer include margins. However, allowing a sidebar to be displayed could disrupt the layout, negatively impact the print appearance, and look less aesthetically pleasing. Therefore, I believe the sidebar and margins should be uniformly removed during printing, and no options for them should be provided.
> 
> What do you think?

Yes, for me it would be ok and reasonable. Because in general a sidebar is actually only needed for viewing within the browser and there is no need on the print layout.

**Comment by Heroor** [comment]
Version 2.16 has been released, please try after updating, if you have other questions, please continue to ask, thank you for your use!
