### ISSUE TITLE
Alerts/admonitions

### ISSUE THREAD

**Issue by plutonium-239** [md-reader/md-reader#63]
**Is your feature request related to a problem? Please describe.**
Alerts/admonitions have been a [github feature](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) for some time now. Other editors like hackmd.io also support it.

**Describe the solution you'd like**
Alerts/admonitions rendered similar to how gfm does.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
Syntax:
```md
> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.
```
How they are rendered:
> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.

**Comment by Heroor** [comment]
Great suggestion! I'll be adding this to subsequent releases.

**Comment by Heroor** [comment]
Alert has been supported in v2.16, please try it after updating, if you have other questions, please continue to ask, thank you for your use!

**Comment by plutonium-239** [comment]
It works and it looks great, thanks!
