### ISSUE TITLE
无法正常显示本地markdown文件

### ISSUE THREAD

**Issue by v-Ys** [md-reader/md-reader#66]
### Describe the bug
无法正常显示本地的markdown文件，权限已打开

### To Reproduce
安装插件开启权限后打开本地markdown文件

### Screenshots
示例文档可以正常预览
<img width="1375" alt="Screenshot 2024-11-25 at 15 59 00" src="https://github.com/user-attachments/assets/0d8b747a-3aec-421f-8aca-976da9f0aff1">

本地文件切换背景会生效，但仅显示源码
<img width="1334" alt="Screenshot 2024-11-25 at 15 57 06" src="https://github.com/user-attachments/assets/3bdc2ea9-2cda-4b9a-b356-f92f8f178e08">

权限正常开启
<img width="712" alt="Screenshot 2024-11-25 at 15 55 43" src="https://github.com/user-attachments/assets/1d472614-88c9-498e-8d12-ee909f77a3f5">

### Desktop
 - macOS
 - Chrome
 - Version 131.0.6778.86 (Official Build) (arm64)

**Comment by Heroor** [comment]
奇怪了，在macOS上一般没什么大问题的，打开权限后有尝试刷新页面吗，在控制台有没有什么报错信息

**Comment by Heroor** [comment]
如果你还安装着的话，可以截图发一下 DOM 结构：

![CleanShot 2024-11-25 at 20 48 03](https://github.com/user-attachments/assets/c63032f7-d2f3-4262-b583-11e7e258e3ca)

**Comment by v-Ys** [comment]
有刷新过的，也试过重启Chrome，并且重装了几次插件都可以复现
### 控制台报错
<img width="1289" alt="Screenshot 2024-11-26 at 12 47 28" src="https://github.com/user-attachments/assets/7eec2f3b-9a0a-412e-867d-31a0d757c810">

### DOM结构
<img width="692" alt="Screenshot 2024-11-26 at 12 46 14" src="https://github.com/user-attachments/assets/0abaf175-350b-461b-afe9-89f1846fe727">

**Comment by v-Ys** [comment]
感谢，确实是文件类型的问题，`.md`后缀会被识别为`text/x-markdown`，改成`.markdown`后缀后被识别为`text/plain`可以正常显示

我修改`etc/apache2/mime.types`后还是无法识别为`text/markdown`，`text/x-markdown`似乎是旧版的`markdown`类型，可否提供一下支持（已提pr）

#### md后缀
<img width="767" alt="Screenshot 2024-11-26 at 17 15 11" src="https://github.com/user-attachments/assets/d5e7f233-fc72-41ce-a489-0c421fef77ae">

#### markdown后缀
<img width="881" alt="Screenshot 2024-11-26 at 17 43 00" src="https://github.com/user-attachments/assets/4e03ff37-5e42-4ecf-bb99-ee5668edade4">

**Comment by Heroor** [comment]
感谢🙏，已合并，这几天会发版，到时候可以更新然后再次尝试一下，如果有问题可以继续提出，祝使用愉快！
